# Numpy

https://numpy.org/

## What is it? 
- Numpy is a Python library used for working with arrays
- Numpy is the fundamental package for scientific computing in Python


## Why do we care? 
- Numpy is one of the main reasons why Python is so powerful and popular for scientific computing
- Super fast. Numpy arrays are implemented in C, which makes numpy very fast.
- The arrays allows for vectorized operations

## Show us! 

### Create a 1D array

#### create a list
format: list()

In [2]:
#create a list
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [4]:
#whats the type
type(my_list)

list

In [459]:
#what is dtype


In [460]:
#whats the shape
# list.shape

#### create an array
format: np.array()

In [5]:
#import numpy as np
import numpy as np

In [7]:
#create the array
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4])

In [8]:
#whats the type
type(my_array)

numpy.ndarray

In [9]:
#whats the shape
my_array.shape

(4,)

In [10]:
my_array.dtype

dtype('int64')

#### access elements of our new array

In [11]:
my_array

array([1, 2, 3, 4])

In [12]:
my_array[0]

1

In [ ]:
my_array[-1]

#### slice the array

In [14]:
my_array[1:] # 1 is INCLUSIVE the second term is ECLUSIVE

array([2, 3, 4])

In [15]:
my_array[:2]

array([1, 2])

In [ ]:
my_array[:2]

#### create an array from 1 to 100

In [18]:
#np.array(?)
a = np.array(range(1,101))
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [19]:
#access single element
a[25]

26

In [20]:
#slice the array! 
a[25:]

array([ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [22]:
a[25:80]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
       77, 78, 79, 80])

### Create a 2D array

In [28]:
#build a list of lists
matrix =[[1,2,3],
 [2,3,4],
 [6,7,8],
 [4,5,6]]
matrix

[[1, 2, 3], [2, 3, 4], [6, 7, 8], [4, 5, 6]]

In [24]:
type(matrix)

list

In [31]:
#turn it into an array! 
matrix_array = np.array(matrix)
matrix_array

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8],
       [4, 5, 6]])

In [27]:
#type
type(matrix_array)

numpy.ndarray

In [32]:
matrix_array.shape

(4, 3)

In [33]:
matrix_array.dtype

dtype('int64')

#### access elements

In [34]:
matrix_array[0]

array([1, 2, 3])

In [35]:
matrix_array[-1]

array([4, 5, 6])

In [36]:
matrix_array[0][0]

1

In [37]:
matrix_array[2,1]

7

### Descriptive Stats

In [38]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

#### using methods: the method is called on the numpy object

In [39]:
# format: object.method()

In [40]:
a.min()

1

In [41]:
a.max()

100

In [43]:
a.std() # population STD ddof delta degrees of freedom defaults to ZERO

28.86607004772212

In [44]:
a.mean()

50.5

#### using functions: using numpy to call functions

In [213]:
np.max(a)

100

In [214]:
np.std(a)

28.86607004772212

In [215]:
np.mean(a)

50.5

In [216]:
np.sum(a)

5050

### Array of Booleans! 

### Boolean Masks

1. create an array
2. make a list of booleans (mask)
3. combine

    format: array [ list of booleans ] 

In [45]:
#pull back our small array
my_array

array([1, 2, 3, 4])

In [46]:
#make list of booleans aka our mask
mask = [True, False, False, True]
mask

[True, False, False, True]

In [47]:
#combine them 
my_array[mask] # only returns values that line up with True-known as BOOLEAN MASKING

array([1, 4])

#### how else can we get our array of boolean values?

In [48]:
my_array

array([1, 2, 3, 4])

In [49]:
#write a conditional with the array
my_array == 4

array([False, False, False,  True])

In [53]:
mask = (my_array == 4)
mask2 = (my_array > 2)

In [52]:
my_array[mask]

array([4])

In [54]:
my_array[mask2]

array([3, 4])

In [55]:
mask.dtype # returns data type of each element in mask-list

dtype('bool')

#### make and apply our boolean mask

array([False, False, False,  True, False])

In [56]:
#format: array_name [ list_of_booleans ]
matrix_array

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8],
       [4, 5, 6]])

In [58]:
mask3 = matrix_array > 3
mask3

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [59]:
matrix_array[mask3]

array([4, 6, 7, 8, 4, 5, 6])

In [60]:
mask4 = (my_array > 2) & (my_array < 4)  # NOTICE & == AND | == OR!!!!!!
mask4

array([False, False,  True, False])

In [61]:
my_array[mask4]

array([3])

#### cool! can we just do it with a list instead of an array?

In [62]:
#pull back our initial list
my_list

[1, 2, 3, 4]

In [63]:
#create a array of booleans
my_list == 4

False

In [488]:
#apply an array of booleans to a list


#### let's bring it back to arrays and make them bigger

In [64]:
#array
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [65]:
#mask
mask = a >= 90
mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [66]:
#boolean mask
a[mask]

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### shortcut?

In [67]:
a[a >= 90]

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
# empty mask (all false) would lead to an EMPTY ARRAY

#### what if we wanted to check two conditions?

In [68]:
# note the parenthesis
# also note that we're using & instead of and
mask = (a > 5) & (a < 15)
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [69]:
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

#### what if we wanted the opposite of our mask?

In [71]:
type(mask)

numpy.ndarray

In [70]:
# the ~ notates the opposite of
~mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [72]:
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
a[~mask]

array([  1,   2,   3,   4,   5,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

## Vectorization Operations
- makes looping over math so easy and fast!

### Add one to every element

#### hard way: doing it in a list

In [74]:
my_list

[1, 2, 3, 4]

In [75]:
mt = []
for i in my_list:
    mt.append(i + 1)
mt

[2, 3, 4, 5]

In [494]:
#using a for loop


In [76]:
#using a list comprehension
[i+1 for i in my_list]

[2, 3, 4, 5]

#### easy way: doing it with an array

In [77]:
my_array

array([1, 2, 3, 4])

In [78]:
my_array + 1

array([2, 3, 4, 5])

In [79]:
my_array ** 2

array([ 1,  4,  9, 16])

In [80]:
np.log(my_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [496]:
#using vectorization operations


### more operations

### show us the speed

In [82]:
#make a really big array
big_array = np.array(range(1_000_001))
big_array

array([      0,       1,       2, ...,  999998,  999999, 1000000])

In [ ]:
# %%timeit

In [88]:
%%timeit

big_array ** 2

478 µs ± 4.64 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [87]:
#make a really big list
big_list = list(big_array)
big_list[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [91]:
%%timeit

for i in big_list:
    i ** 2

69.6 ms ± 51.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Numpy ways to create arrays

#### full of zeros

In [92]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### full of ones

In [93]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [95]:
len(np.ones(10_000))

10000

#### full of whatever you want 

In [96]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [97]:
np.full(10, True)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [98]:
np.full((10,2),3)

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

#### a quicker way to make a range

In [99]:
# np.array(range(100))
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### an array of random integers

In [100]:
#np.random.randint()
np.random.randint(2,20,10)

array([ 3, 18, 18,  7,  5, 14,  7,  7, 12,  4])

In [103]:
np.random.randint(0,200,21)

array([ 58,  15, 136,  85,  38,  59,  96, 196, 174, 114,  28,  88,  83,
        63,   3,  82,  96,  18, 137,  78,   8])

#### an array of random numbers from the standard distribution

In [104]:
#np.random.randn()
np.random.randn(10)

array([ 0.93817794, -2.50576531,  1.01469019,  0.49081545,  0.7867029 ,
       -1.81173255,  0.92742206, -0.44092345,  0.25324084,  1.49440219])