## numpy_exercises

In [1]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [2]:
a[(a < 0)]

array([-2, -1, -6, -7])

In [3]:
(a < 0)

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [4]:
# 1 How many neg numbers
(a < 0).sum()

4

In [5]:
# 2 How many pos numbers
(a > 0).sum()

5

In [6]:
a.shape

(12,)

In [7]:
# 3 How many POS EVEN nums
mask = (a > 0) & (a % 2 == 0)
mask

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False])

In [8]:
# count the true bools in mask
mask.sum()

3

In [9]:
# 4 add 3 to each data point--how many POS INT do you have now?
a_plus3 = (a + 3)
a_plus3


array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [10]:
# count the True bools in mask2
mask2 = (a_plus3 > 0)&(a_plus3 % 1 == 0)
mask2
mask2.sum()

10

In [11]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [12]:
# 5 square each num what is new mean and std?
a_sqd = (a ** 2)
a_sqd

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [13]:
a_sqd.mean()

74.0

In [14]:
round(a_sqd.std(),2)

144.02

In [15]:
# 6 Center the data about mean = 0 using the data from a
# obtain mean of a
a.mean()

3.0

In [16]:
# subtract mean from each data point
a_centered = (a - 3)
a_centered

array([  1,   7,   9,  20,  -5,  -4,  -3,  -3,  -3,  -9,   0, -10])

In [17]:
a_centered.mean()

0.0

In [18]:
# 7 Calc the Z-score for each data point
std_a = a_centered.std()
std_a

8.06225774829855

two ways to do it

In [19]:
zscores_a = (a_centered - a_centered.mean()) / std_a
zscores_a.round(3)

array([ 0.124,  0.868,  1.116,  2.481, -0.62 , -0.496, -0.372, -0.372,
       -0.372, -1.116,  0.   , -1.24 ])

In [20]:
zscores_a2 = (a - a.mean()) / a.std()
zscores_a2.round(3)

array([ 0.124,  0.868,  1.116,  2.481, -0.62 , -0.496, -0.372, -0.372,
       -0.372, -1.116,  0.   , -1.24 ])

## SETUP numpy_ex_p1

In [21]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:

In [22]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a= sum(a)
sum_of_a

55

In [23]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)
min_of_a

1

In [24]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
max_of_a

10

In [25]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
import statistics as stats
mean_of_a = stats.mean(a)
mean_of_a

5.5

In [ ]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
# product_of_a = 1
# for i in a:
#     a *= i
# product_of_a

In [26]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = [i ** 2 for i in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [27]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = [i for i in a if int(i) % 2 != 0]
odds_in_a

[1, 3, 5, 7, 9]

In [28]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = [i for i in a if int(i) % 2 == 0]
evens_in_a

[2, 4, 6, 8, 10]

In [29]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [30]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
# sum_of_b = 0
# for row in b:
#     sum_of_b += sum(row)

matrix_b = np.array(b)

sum_of_b = np.sum(matrix_b)
sum_of_b

33

In [31]:
matrix_b

array([[3, 4, 5],
       [6, 7, 8]])

In [32]:
# Exercise 2 - refactor the following to use numpy. 
# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

min_of_b = matrix_b.min()
min_of_b

3

In [33]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = np.max(matrix_b)
max_of_b

8

In [34]:
# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b = np.mean(matrix_b)
mean_of_b

5.5

In [35]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
# product_of_b = 1
# for row in b:
#     for number in row:
#         product_of_b *= number

cumprod_of_b_list = np.cumprod(matrix_b)
cumprod_of_b_int = cumprod_of_b_list[-1]
cumprod_of_b_int

20160

In [36]:
matrix_b

array([[3, 4, 5],
       [6, 7, 8]])

In [37]:
matrix_b ** 2

array([[ 9, 16, 25],
       [36, 49, 64]])

In [38]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
# squares_of_b = []
# for row in b:
#     for number in row:
#         squares_of_b.append(number**2)

squares_of_b = matrix_b ** 2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [39]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
# odds_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 != 0):
#             odds_in_b.append(number)

mask_odds = matrix_b % 2 != 0
odds_in_b = matrix_b[mask_odds]
odds_in_b

array([3, 5, 7])

In [40]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
# evens_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 == 0):
#             evens_in_b.append(number)

mask_evens = matrix_b % 2 == 0
evens_in_b = matrix_b[mask_evens]
evens_in_b

array([4, 6, 8])

In [41]:
# Exercise 9 - print out the shape of the array b.

matrix_b.shape

(2, 3)

In [42]:
# Exercise 10 - transpose the array b.
np.transpose(matrix_b).shape

(3, 2)

In [43]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
matrix_b.reshape(1,6)

array([[3, 4, 5, 6, 7, 8]])

In [44]:
np.reshape(matrix_b,(1,6))

array([[3, 4, 5, 6, 7, 8]])

In [45]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
matrix_b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [46]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [47]:
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

matrix_c = np.array(c)
matrix_c

print(matrix_c.min())
print(matrix_c.max())
print(matrix_c.sum())
cumprod_of_c_list = np.cumprod(matrix_c)
cumprod_of_c_int = cumprod_of_c_list[-1]
cumprod_of_c_int

1
9
45


362880

In [48]:
# Exercise 2 - Determine the standard deviation of c.

round(matrix_c.std(),3)

2.582

In [49]:
# Exercise 3 - Determine the variance of c.
round(matrix_c.var(),3)

6.667

In [50]:
# Exercise 4 - Print out the shape of the array c

matrix_c.shape

(3, 3)

In [51]:
# Exercise 5 - Transpose c and print out transposed result.
matrix_c_trpose = np.transpose(matrix_c)
matrix_c_trpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [52]:
# Exercise 6 - Get the dot product of the array c with c. 

np.dot(matrix_c,matrix_c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [53]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

matrix_c_prod_matrix_c_trpose = matrix_c * matrix_c_trpose
matrix_c_prod_matrix_c_trpose.sum()

261

In [54]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
matrix_c_prod_matrix_c_trpose

cumprod_of_cnc_list = np.cumprod(matrix_c_prod_matrix_c_trpose)
cumprod_of_cnc_int = cumprod_of_cnc_list[-1]
cumprod_of_cnc_int

# cumprod_of_c_list = np.cumprod(matrix_c)
# cumprod_of_c_int = cumprod_of_c_list[-1]
# cumprod_of_c_int

131681894400

In [55]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [56]:
matrix_d = np.array(d)
matrix_d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [57]:
# Exercise 1 - Find the sine of all the numbers in d

np.sin(matrix_d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [58]:
# Exercise 2 - Find the cosine of all the numbers in d

np.cos(matrix_d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [59]:
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(matrix_d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [60]:
matrix_d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [61]:
# Exercise 4 - Find all the negative numbers in d

# mask_evens = matrix_b % 2 == 0
# evens_in_b = matrix_b[mask_evens]
# evens_in_b

mask_neg = matrix_d < 0
neg_in_d = matrix_d[mask_neg]
neg_in_d

array([-90, -30, -45, -45])

In [62]:
# Exercise 5 - Find all the positive numbers in d

mask_pos = matrix_d > 0
pos_in_d = matrix_d[mask_pos]
pos_in_d

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [63]:
# Exercise 6 - Return an array of only the unique numbers in d.

np.unique(matrix_d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [64]:
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(matrix_d))

11

In [65]:
# Exercise 8 - Print out the shape of d.

matrix_d.shape

(3, 6)

In [66]:
# Exercise 9 - Transpose and then print out the shape of d.

matrix_d_trpose = np.transpose(matrix_d)
matrix_d_trpose.shape

(6, 3)

In [67]:
# Exercise 10 - Reshape d into an array of 9 x 2

matrix_d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])